- hosts: all
  name: Setup common infrastructure (Docker and Network)
  roles:
    - docker
    - network

- hosts: all
  name: Deploy Database Service
  tags: [database]
  roles:
    - database

- hosts: all
  name: Deploy Application Service
  tags: [app]
  roles:
    - app

- hosts: all
  name: Deploy Proxy Service
  tags: [proxy]
  roles:
    - proxy